openapi: 3.2.0
info:
  title: Fast Event Handler API
  version: 0.1.0
tags:
- name: Event Handler
paths:
  /slack/events:
    post:
      tags:
      - Event Handler
      summary: ' Handle Slack Events'
      description: Slack Webhook Handler. Used to do things like respond to users that mention the app or use our `/akkio` command.
      operationId: _handle_slack_events_slack_events_post
      responses:
        '200':
          description: Successful Response
          content:
            text/plain:
              schema:
                type: string
