openapi: 3.2.0
info:
  title: Fast Transforms API
  version: 0.1.0
tags:
- name: Transforms
paths:
  /transforms/new:
    post:
      tags:
      - Transforms
      summary: ' Handle New Transform'
      description: Initialize a transform. We'll return a task_id that you can use to check the status of the transform. You can also retrieve a task_id for a currently running transform via the flow_id, which enables us to support people leaving and coming back to the transform.
      operationId: _handle_new_transform_transforms_new_post
      requestBody:
        content:
          application/json:
            schema:
              title: Body
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APITaskStartedResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /transforms/get-most-recent-task-id-by-dataset-id:
    get:
      tags:
      - Transforms
      summary: ' Handle Get Most Recent Task Id By Flow Id'
      description: Get the most recent task_id of a transform run on this dataset. You can then use this to look up the status of it, and from there the result.
      operationId: _handle_get_most_recent_task_id_by_flow_id_transforms_get_most_recent_task_id_by_dataset_id_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                anyOf:
                - type: string
                - type: 'null'
                title: Response  Handle Get Most Recent Task Id By Flow Id Transforms Get Most Recent Task Id By Dataset Id Get
  /transforms/status/{task_id}:
    get:
      tags:
      - Transforms
      summary: ' Handle Transform Status'
      description: Query the status of a currently running transform. If complete, the location of a result will be provided -- query that location with a GET to receive the result. If failed, the error will be provided.
      operationId: _handle_transform_status_transforms_status__task_id__get
      parameters:
      - name: task_id
        in: path
        required: true
        schema:
          type: string
          title: Task Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIStatusResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /transforms/results/{task_id}:
    get:
      tags:
      - Transforms
      summary: ' Handle Transform Result'
      description: Get the result of the transform performed under the given task_id.
      operationId: _handle_transform_result_transforms_results__task_id__get
      parameters:
      - name: task_id
        in: path
        required: true
        schema:
          type: string
          title: Task Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    APIStatusMetadataSucceeded:
      properties:
        type:
          type: string
          enum:
          - SUCCEEDED
          const: SUCCEEDED
          title: Type
          default: SUCCEEDED
        location:
          type: string
          title: Location
          description: The path at which you can submit a GET request to retrieve the result of the successful job. May require proper authentication or authorization to access.
      additionalProperties: true
      type: object
      required:
      - location
      title: APIStatusMetadataSucceeded
    APIStatusMetadataFailed:
      properties:
        type:
          type: string
          enum:
          - FAILED
          const: FAILED
          title: Type
          default: FAILED
        error:
          type: string
          title: Error
          description: If provided, a text representation of what went wrong with the task, including if any action on your part may rectify the issue.
          default: Unable to complete request. Please verify your inputs, try again later, or get in touch at support@akkio.com.
      additionalProperties: true
      type: object
      title: APIStatusMetadataFailed
    APIStatusResponse:
      properties:
        status:
          $ref: '#/components/schemas/TaskStatusEnum'
          description: The current status of the task being queried.
        metadata:
          oneOf:
          - $ref: '#/components/schemas/APIStatusMetadataPending'
          - $ref: '#/components/schemas/APIStatusMetadataInProgress'
          - $ref: '#/components/schemas/APIStatusMetadataSucceeded'
          - $ref: '#/components/schemas/APIStatusMetadataFailed'
          title: Metadata
          description: Metadata, contextually dependent on the status of the task being queried.
          discriminator:
            propertyName: type
            mapping:
              FAILED: '#/components/schemas/APIStatusMetadataFailed'
              IN_PROGRESS: '#/components/schemas/APIStatusMetadataInProgress'
              PENDING: '#/components/schemas/APIStatusMetadataPending'
              SUCCEEDED: '#/components/schemas/APIStatusMetadataSucceeded'
      additionalProperties: true
      type: object
      required:
      - status
      - metadata
      title: APIStatusResponse
    TaskStatusEnum:
      type: string
      enum:
      - PENDING
      - IN_PROGRESS
      - SUCCEEDED
      - FAILED
      - UNKNOWN_TIMEOUT
      title: TaskStatusEnum
      description: Celery task status enum. Update apps/web-backend-api/src/types/TaskStatusEnum.ts if you update this enum.
    APITaskStartedResponse:
      properties:
        task_id:
          type: string
          title: Task Id
          description: The ID of the task that was started. This is generally queryable at a nearby `/status` endpoint to get the current status of the task.
      additionalProperties: true
      type: object
      required:
      - task_id
      title: APITaskStartedResponse
    APIStatusMetadataPending:
      properties:
        type:
          type: string
          enum:
          - PENDING
          const: PENDING
          title: Type
          default: PENDING
      additionalProperties: true
      type: object
      title: APIStatusMetadataPending
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    APIStatusMetadataInProgress:
      properties:
        type:
          type: string
          enum:
          - IN_PROGRESS
          const: IN_PROGRESS
          title: Type
          default: IN_PROGRESS
        estimate_seconds:
          anyOf:
          - type: number
          - type: 'null'
          title: Estimate Seconds
          description: If provided, an estimate of how many seconds we expect this task to take. This value should be treated as a rough estimate on a best-effort basis, not a guarantee.
      additionalProperties: true
      type: object
      title: APIStatusMetadataInProgress
